### ISSUE TITLE
Question: regarding dynamic discovery strategy changing at runtime/startup

### ISSUE THREAD

**Issue by bitsofinfo** [bitsofinfo/hazelcast-consul-discovery-spi#10]
author:@pheitman 

This looks like exactly what I need – but I’m having one key problem. Our application is Spring-based and I want to make this network strategy conditional on being in a deployment using consul. The spring xsd does not have the “enabled” attribute for the discovery strategy, unlike the other three options for the network join. Is there any examples that describe how to support conditionally enabling the discovery strategy? Possibly extending the class to look for an enabled property?

**Comment by bitsofinfo** [comment]
Hazelcast XML config files support a notation of property replacement such as "${systemProp}" etc. So you could have one hazelcast xml config file in your artifact, but for all the discovery portions of the config do something like

```
<multicast enabled="${hz.discovery.multicast.enabled}">
      <multicast-group>224.2.2.3</multicast-group>
     <multicast-port>54327</multicast-port>
 </multicast> 
<discovery-strategies>
  <discovery-strategy enabled="${hz.discovery.consul.enabled}"
            class="org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategy">
```

Then when you startup your java app do something like 

```
java -jar myapp.jar -Dhz.discovery.multicast.enabled=true -Dhz.discovery.consul.enabled=false
```

This section may explain too: https://github.com/bitsofinfo/hazelcast-consul-discovery-spi#docker

**Comment by pheitman** [comment]
Thank you for the quick reply! Yes, I've tried that - which is how I found out that the "enabled" attribute is not available in the xsd for hazelcast with spring (see https://hazelcast.com/schema/spring/hazelcast-spring-3.6.xsd). Even if I try to set it to "false" it still runs the consul discovery

**Comment by bitsofinfo** [comment]
Oh, well not sure how to help you other than don't use the Spring bean XSD based summarized configuration method. Go straight to the lower level hazelcast xml configuration based method and you will have more control (i.e. create your own hazelcast.xml config file and feed hazecast w/ that). That's what I do in production and the above method works w/ the property replacement.

We have just one hazelcast config file, and we use the system props to toggle what discovery mech to use in different environments and/or containers.

```
xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.6.xsd"
```

**Comment by pheitman** [comment]
Ok, thanks for the quick answers. Unfortunately I don't control the use of Spring within our application. It is a general design philosophy that is used throughout. I've been advised to wrap your class and make it conditional on an enabled property and was hoping that someone had already addressed this - but I recognize that it is an edge case that may not have been seen before.

**Comment by bitsofinfo** [comment]
We use spring, but just don't configure HZ via spring xml, we have a wrapper service that instantiates and configures HZ inside of it, and just point it to the config as such.

```
  <bean id="hazelcastGridService" class="my.package.HazelcastGridService">
     <constructor-arg value="path/to/hazelcast.xml"/>
  </bean> 
```

You could do the same w/ a factory bean that invokes hz get instance passing the config in spring too.

Anyways, if you come up w/ a solution that might be useful to others and its generic enough/non-disruptive feel free to submit a PR

Also maybe submit a bug/issue to hazelcast and let them know that enabled functionality does not work w/ the spring xsd method of configuring HZ
