### ISSUE TITLE
Any chance for an RC5 that uses the most recent consul-client?

### ISSUE THREAD

**Issue by pheitman** [bitsofinfo/hazelcast-consul-discovery-spi#11]
When I try to use RC4 of hazelcast-consul-discovery-spi with wildfly 8.2.0.Final, I get into a jar conflict with the com.fasterxml.jackson.core jars. This seems to happen because RC4 uses version 0.10.0 of consul-client which depended on specific versions of those jar files. Resteasy from jboss uses different versions. Versions of consul-client later than 0.11.X addressed this by including the classes within the jar in such a way that the dependencies were resolved locally instead of using the class loader to load them. 

I did a test where I changed the pom file hazelcast-consul-discovery-spi-1.0-RC4.pom, changing the dependency for consul-client to be version 0.12.4 from 0.10.0. AFAICT the hazelcast-discovery functionality worked fine and my problems with jar conflicts disappeared.

Is there any chance that an RC5 could be published that changed the dependency for consul-client to make this "official"?

**Comment by bitsofinfo** [comment]
Please submit a PR, rerun all tests before, and I'll try to get it in, thanks!

subscribing @bmudda

**Comment by pheitman** [comment]
Sorry that it has taken me so long to get back to you on this. I've finally downloaded the zip and run the tests. There are significant issues. First, the following compile groups need to be added to build.gradle:

```
compile group: 'com.orbitz.consul', name: 'consul-client', version:'0.12.4'
compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version:'2.6.3'
compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version:'2.6.3'
compile group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version:'2.6.3'
compile group: 'org.glassfish.jersey.core', name: 'jersey-client', version:'2.9.1'
```

(note that this replaces the compile group for the older consul-client)

But the big problem is that the Consul.Builder class no longer has the method withClientBuilder() that is used in ConsulClientBuilder when consulServerHostnameVerify is false. I've apparently lucked out because the default is true so this method isn't called in my environment. The compilation fails. It unfortunately isn't as simple as just using the latest version of consul-client.

**Comment by bitsofinfo** [comment]
@pheitman 

I'll take a look, will the latest hz 3.6.4 lib be an issue for you?

**Comment by bitsofinfo** [comment]
https://github.com/OrbitzWorldwide/consul-client/issues/145

**Comment by bitsofinfo** [comment]
Done, in RC5, consul-client 0.12.5

**Comment by pheitman** [comment]
Thank you! I'll give it a try next chance I get
