### ISSUE TITLE
consul-acl-token isn't optional

### ISSUE THREAD

**Issue by nickcodefresh** [bitsofinfo/hazelcast-consul-discovery-spi#12]
I'm trying to configure Hazelcast usin the following code:

```
        Map<String, Comparable> properties = new HashMap<>();
        properties.put("consul-host", "localhost");
        properties.put("consul-port", "8500");
        properties.put("consul-service-name", "abc");
        properties.put("consul-healthy-only", "true");
        properties.put("consul-service-tags", "LocalDiscoveryNodeRegistrator");
        properties.put("consul-discovery-delay-ms", "10000");
        properties.put("consul-registrator", "org.bitsofinfo.hazelcast.discovery.consul.LocalDiscoveryNodeRegistrator");
        properties.put("consul-registrator-config", consulRegistratorConfig);

        DiscoveryStrategyConfig discoveryStrategyConfig = new DiscoveryStrategyConfig(
                "org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategy", properties);
        discoveryConfig.addDiscoveryStrategyConfig(discoveryStrategyConfig);
```

When I run it though it tells me that the `consul-acl-token` property is mandatlry. It should be optional according to https://github.com/bitsofinfo/hazelcast-consul-discovery-spi/blob/master/src/main/resources/hazelcast-consul-discovery-spi-example.xml.

Any idea what I'm doing wrong here?

Thanks

Nick

**Comment by bmudda** [comment]
Hey Nick, did you try putting "consul-acl-token" in your properties map with empty string? The property itself is required, but if there is no value, then it skips the ACL check.

**Comment by bitsofinfo** [comment]
@nickcodefresh did @bmudda suggestion help?

**Comment by nickcodefresh** [comment]
Yes that worked, but it seems a bit odd to me to have to do that! Thanks @bmudda anyway

**Comment by bitsofinfo** [comment]
@bmudda submit a PR to fix this I guess
