### ISSUE TITLE
Unable to discover cluster members

### ISSUE THREAD

**Issue by rtv2222** [bitsofinfo/hazelcast-consul-discovery-spi#19]
Hi,

I am trying to get Hazelcast to discover its cluster members via consul using this plugin.

Hazelcast version : 3.7.5
hazelcast-consul-discovery-spi : 1.0-RC7
com.orbitz.consul.consul-client : 0.13.11-shaded.jar

I have two vms reachable from one another 10.78.106.136 and 10.78.106.137. I am running consul server on 136 and an agent on 137. Here is the output of **consul members**

Node       Address             Status  Type    Build  Protocol  DC
agent-one  10.78.106.136:8301  alive   server  0.8.3  2         dc1
agent-two  10.78.106.137:8301  alive   client  0.8.3  2         dc1

I however am not able to see both the cluster members when I do a hazelcastInstance.getCluster().getMembers(). It always only shows the node on which the call is made.

Here is my cluster.xml
[cluster.txt](https://github.com/bitsofinfo/hazelcast-consul-discovery-spi/files/1044113/cluster.txt)

I see these messages in the logs

[10.78.106.137]:5801 [host_telemetry_cluster_229] [3.7.5] Connection[id=30, /10.78.106.137:5801->/10.78.106.137:47788, endpoint=null, alive=false, type=NONE] closed. Reason: Connection closed by the other side
2017-06-01 13:55:06,417 WARN  [hz._hzInstance_1_host_telemetry_cluster_229.IO.thread-out-2] Slf4jFactory$Slf4jLogger -   [10.78.106.137]:5801 [host_telemetry_cluster_229] [3.7.5] SocketWriter is not set, creating SocketWriter with CLUSTER protocol!

and hence turned off auto-increment on cluster.xml. The logs continue to show up the error though.

I also see these exceptions from the consul client

Caused by: java.io.EOFException: \n not found: size=0 content=…
       	at com.orbitz.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215) ~[consul-client-0.13.11-shaded.jar:?]

Caused by: java.io.IOException: unexpected end of stream on com.orbitz.okhttp3.Address@145f72d1
Unexpected error in configuring discovery: Error connecting to Consul
com.orbitz.consul.ConsulException: Error connecting to Consul
       	at com.orbitz.consul.AgentClient.ping(AgentClient.java:65) ~[consul-client-0.13.11-shaded.jar:?]

I am configuring the consul server address in the cluster.xml on both vms. Using 127.0.0.1 does not help either.

What could I be doing wrong ? It appears I am only trying the most basic use case here.

Thanks,
Rajesh

**Comment by bitsofinfo** [comment]
You are using the `org.bitsofinfo.hazelcast.discovery.consul.DoNothingRegistrator` which does nothing (other than attempt to lookup service info) and relies on you manually registering your services w/ consul via some other means. See the README for info on the other options like `LocalDiscoveryNodeRegistrator` which will auto register each HZ instance.

Also you would likely want each HZ member node to talk to its local consul agent, not the remote consul server (agents connect to servers). It should still work but just an FYI

Also if you are having connection issues, are you sure your consul is not running https? Do you have the right port configured etc? 8301 is diff, typically 8500 or 8501

**Comment by rtv2222** [comment]
I did go over the README multiple times and started with the LocalDiscoveryNodeRegistrator and the consul server ip set to 127.0.0.1. I only need hazelcast to use consul for discovery of all cluster nodes and do not require services to be auto-registered in consul. I hence thought the DoNothingRegistrator was more appropriate. Here is the error I see when I use a LocalDiscoveryNodeRegistrator with 127.0.0.1 as the consul server ip. Please note the consul is running as the agent in one vm and as a server on the other.

[cluster.withLocalDiscoveryNodeRegistrar.txt](https://github.com/bitsofinfo/hazelcast-consul-discovery-spi/files/1045375/cluster.withLocalDiscoveryNodeRegistrar.txt)

Caused by: java.net.ConnectException: Failed to connect to /127.0.0.1:8301

If I change the port 8500 at <property name="consul-port">8500</property> I get the following errors from hazelcast

2017-06-01 21:40:43,110 INFO  [hz._hzInstance_1_host_telemetry_cluster_229.IO.thread-in-1] Slf4jFactory$Slf4jLogger -   [10.78.106.136]:5801 [host_telemetry_cluster_229] [3.7.5] Connection[id=8, /10.78.106.136:5801->/10.78.106.136:34739, endpoint=null, alive=false, type=NONE] closed. Reason: Connection closed by the other side
2017-06-01 21:40:43,111 WARN  [hz._hzInstance_1_host_telemetry_cluster_229.IO.thread-out-1] Slf4jFactory$Slf4jLogger -   [10.78.106.136]:5801 [host_telemetry_cluster_229] [3.7.5] SocketWriter is not set, creating SocketWriter with CLUSTER protocol!

The consul members do not show up in the hazelcast instance.

I'll be more than happy to star this effort once I get it working. Thanks in advance.

**Comment by bitsofinfo** [comment]
Well the error you are posting is a simple connectivity error. 

And you are certain that the local consul agent is listening on the loopback interface on 8301?

Can you telnet to it?

**Comment by rtv2222** [comment]
telnet 10.78.106.136 8301
Trying 10.78.106.136...
Connected to 10.78.106.136.
Escape character is '^]'.

I changed the loopback to the WAN ip to which I can telnet and I now hit the first set of errors

Caused by: java.io.EOFException: \n not found: size=0 content=…
Caused by: java.io.IOException: unexpected end of stream on com.orbitz.okhttp3.Address@77d1e684

No luck with discovering cluster members yet.

Could you clarify if I really need the LocalDiscoveryNodeRegistrator if only want Hazelcast to discover consul members ?

Thanks,
Rajesh

**Comment by bitsofinfo** [comment]
if you are using `LocalDiscoveryNodeRegistrator` it is assumed that you have manually registered a consul service entry named `hz-discovery-test-cluster` in consul w/ the appropriate nodes/ports of your hz members.

**Comment by rtv2222** [comment]
I do see the services registered in consul for both the nodes.

Do you have any inputs on why I might be hitting the errors that I seeing ?

curl http://localhost:8500/v1/catalog/service/hz-discovery-test-cluster
[{"ID":"bfb8b29b-945d-0bfb-897a-24ab3b1e06b3","Node":"agent-one","Address":"10.78.106.136","Datacenter":"dc1","TaggedAddresses":{"lan":"10.78.106.136" 
--Am clipping the rest of the output--

**Comment by bitsofinfo** [comment]
So for the above you are accessing consul on localhost:8500... yet your SPI config is going to localhost:8301

Have the SPI connect to port 8500, not 8301

**Comment by rtv2222** [comment]
I did just as you suggest above. The port is accessible, consul members report both nodes, curl works fine too but hazelcast does not seem to see the cluster nodes. Here is the new cluster.xml as per your suggestion

[cluster.withLocalDiscoveryNodeRegistrar.txt](https://github.com/bitsofinfo/hazelcast-consul-discovery-spi/files/1046742/cluster.withLocalDiscoveryNodeRegistrar.txt)


$ telnet localhost 8500
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

$ curl http://localhost:8500/v1/catalog/service/hz-discovery-test-cluster
[{"ID":"bfb8b29b-945d-0bfb-897a-24ab3b1e06b3","Node":"agent-one","Address":"10.78.106.136"
----some output clipped---
"Address":"10.78.106.137"
---some outputclipped ---

$ consul members
Node       Address             Status  Type    Build  Protocol  DC
agent-one  10.78.106.136:8301  alive   server  0.8.3  2         dc1
agent-two  10.78.106.137:8301  alive   client  0.8.3  2         dc1

hazelcastInstance.getCluster().getMembers() however only gives me one member

Not sure what else I could try. Would appreciate if you have any suggestions.

**Comment by rtv2222** [comment]
I figured out the problem.
I was missing this property to be set to enable SPI based discovery

  <properties>
    <property name="hazelcast.discovery.enabled">true</property>
  </properties>

as illustrated here http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#discovery-spi 

With this set, the plugin works like a charm. Thanks for your help.

**Comment by ksskSantosh** [comment]
Hi @rtv2222  
Can I have the configuration of Json you had used.
