### ISSUE TITLE
Not able to get ExplicitIpPortRegistrator working

### ISSUE THREAD

**Issue by vigneshsenapathy** [bitsofinfo/hazelcast-consul-discovery-spi#23]
I am using "ExplicitIpPortRegistrator"

My hazelcast.xml looks like this

<?xml version="1.0" encoding="UTF-8"?>
<hazelcast id="hazelcast-consul-discovery" 
           xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.6.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>hazelcast-consul-discovery-spi</name>
        <password>haz3lcast1</password>
    </group>

    <properties>
        <property name="hazelcast.discovery.enabled">true</property>
        <property name="hazelcast.shutdownhook.enabled">false</property>
        <property name="hazelcast.phone.home.enabled">false</property>
        <property name="hazelcast.mancenter.enabled">false</property>
        <property name="hazelcast.memcache.enabled">false</property>
        <property name="hazelcast.rest.enabled">false</property>
        <property name="hazelcast.wait.seconds.before.join">5</property>
        <property name="hazelcast.operation.thread.count">1</property>
        <property name="hazelcast.operation.generic.thread.count">1</property>
        <property name="hazelcast.client.event.thread.count">1</property>
        <property name="hazelcast.event.thread.count">1</property>
        <property name="hazelcast.heartbeat.interval.seconds">5</property>
        <property name="hazelcast.max.no.heartbeat.seconds">30</property>
        <property name="hazelcast.icmp.enabled">true</property>
        <property name="hazelcast.icmp.timeout">5000</property>
        <property name="hazelcast.icmp.ttl">3</property>
        <property name="hazelcast.merge.next.run.delay.seconds">15</property>       
    </properties>

    <network>
        <port auto-increment="true">2434</port>
        
        <join>
            <multicast enabled="false"/>
            <aws enabled="false"/>
            <tcp-ip enabled="false" />
              
             <discovery-strategies>
        
               <discovery-strategy enabled="true"
                   class="org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategy">
        
                 <properties>
                      <property name="consul-host">172.17.0.1</property>
                      <property name="consul-port">8500</property>
                      <property name="consul-service-name">orientdb</property>
                      <property name="consul-healthy-only">true</property>
                      <property name="consul-discovery-delay-ms">0</property>
                      
                      <property name="consul-acl-token"></property>
				              <property name="consul-ssl-enabled">false</property>
					            <property name="consul-ssl-server-cert-file-path"></property>
					            <property name="consul-ssl-server-cert-base64"></property>
					            <property name="consul-ssl-server-hostname-verify">false</property>					  
                      <property name="consul-registrator">org.bitsofinfo.hazelcast.discovery.consul.ExplicitIpPortRegistrator</property>
                      <property name="consul-registrator-config"><![CDATA[
                          {
                              "registerWithIpAddress":"MYIP",
                              "registerWithPort":2434, 
                              "healthCheckProvider":"org.bitsofinfo.hazelcast.discovery.consul.ScriptHealthCheckBuilder",
                              "healthCheckScript":"exec 6<>/dev/tcp/MYIP/SERVICE_PORT || (exit 3)",
                              "healthCheckScriptIntervalSeconds":30,
                              "healthCheckHttp":"http://MYIP:80",
                              "healthCheckHttpIntervalSeconds":30,
                              "healthCheckTcp":"MYIP:SERVICE_PORT",
                              "healthCheckTcpIntervalSeconds":30
                          }]]>
                      </property>                            
                 </properties>
               </discovery-strategy>
             </discovery-strategies>
              
        </join>
    </network>
</hazelcast>

I got the following error when i start up orient db which uses hazelcast:

2017-09-18 16:49:59:230 INFO  [172.17.0.1]:2434 [hazelcast-consul-discovery-spi] [3.8.4] Determined local DiscoveryNode address to use: [10.210.56.20]:2434 [DiscoveryService]Exception in thread "Thread-0" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.type.ReferenceType.upgradeFrom(Lcom/fasterxml/jackson/databind/JavaType;Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/type/ReferenceType;

**Comment by vigneshsenapathy** [comment]
@bitsofinfo : i tried the do nothingregistrator and i got the following error

  	 line:	 2017-09-18 18:09:09:343 INFO  [172.17.0.1]:5701 [hazelcast-consul-discovery-spi] [3.8.4] Using ConsulRegistrator: org.bitsofinfo.hazelcast.discovery.consul.DoNothingRegistrator [DiscoveryService]Exception in thread "Thread-0" java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonFormat$Value.empty()Lcom/fasterxml/jackson/annotation/JsonFormat$Value;

**Comment by vigneshsenapathy** [comment]
+--- com.hazelcast:hazelcast:3.7+ -> 3.7.8
+--- com.orbitz.consul:consul-client:0.13.12
|    +--- com.squareup.retrofit2:retrofit:2.1.0
|    |    \--- com.squareup.okhttp3:okhttp:3.3.0
|    |         \--- com.squareup.okio:okio:1.8.0
|    +--- com.squareup.retrofit2:converter-jackson:2.0.2
|    |    +--- com.squareup.retrofit2:retrofit:2.0.2 -> 2.1.0 (*)
|    |    \--- com.fasterxml.jackson.core:jackson-databind:2.7.2 -> 2.7.4
|    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.7.0 -> 2.7.4
|    |         \--- com.fasterxml.jackson.core:jackson-core:2.7.4
|    +--- com.google.guava:guava:19.0
|    +--- com.google.code.findbugs:jsr305:1.3.9
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.7.4
|    +--- com.fasterxml.jackson.core:jackson-core:2.7.4
|    +--- com.fasterxml.jackson.core:jackson-databind:2.7.4 (*)
|    +--- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.7.4
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.7.4 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.7.4
|    |    \--- com.google.guava:guava:16.0 -> 19.0
|    +--- org.apache.commons:commons-lang3:3.4
|    \--- org.slf4j:slf4j-api:1.7.21
+--- commons-codec:commons-codec:1.8
+--- org.apache.cxf:cxf-rt-rs-client:3.0.3
|    +--- org.apache.cxf:cxf-rt-transports-http:3.0.3
|    |    \--- org.apache.cxf:cxf-core:3.0.3
|    |         +--- org.codehaus.woodstox:woodstox-core-asl:4.4.1
|    |         |    \--- org.codehaus.woodstox:stax2-api:3.1.4
|    |         \--- org.apache.ws.xmlschema:xmlschema-core:2.1.0
|    +--- org.apache.cxf:cxf-core:3.0.3 (*)
|    \--- org.apache.cxf:cxf-rt-frontend-jaxrs:3.0.3
|         +--- org.apache.cxf:cxf-core:3.0.3 (*)
|         +--- javax.ws.rs:javax.ws.rs-api:2.0.1
|         +--- javax.annotation:javax.annotation-api:1.2
|         \--- org.apache.cxf:cxf-rt-transports-http:3.0.3 (*)
+--- org.apache.cxf:cxf-rt-transports-http-hc:3.0.3
|    +--- org.apache.cxf:cxf-core:3.0.3 (*)
|    +--- org.apache.cxf:cxf-rt-transports-http:3.0.3 (*)
|    +--- org.slf4j:slf4j-api:1.7.7 -> 1.7.21
|    +--- org.apache.httpcomponents:httpcore-nio:4.3.3
|    |    \--- org.apache.httpcomponents:httpcore:4.3.3
|    \--- org.apache.httpcomponents:httpasyncclient:4.0.2
|         +--- org.apache.httpcomponents:httpcore:4.3.2 -> 4.3.3
|         +--- org.apache.httpcomponents:httpcore-nio:4.3.2 -> 4.3.3 (*)
|         \--- org.apache.httpcomponents:httpclient:4.3.5
|              +--- org.apache.httpcomponents:httpcore:4.3.2 -> 4.3.3
|              \--- commons-codec:commons-codec:1.6 -> 1.8
\--- junit:junit:4.12
     \--- org.hamcrest:hamcrest-core:1.3

**Comment by bitsofinfo** [comment]
You may want to exclude the transitive dependency of jackson from the consul-cilent dependency. Not sure but it looks like the version conflicts with another you have in your pom etc.

**Comment by vigneshsenapathy** [comment]
@bitsofinfo : So the method is this dependent on 2.7.2 or 2.7.4 of jackson-databind
The reason i am asking is because this is the only place i am seeing it
|    |    \--- com.fasterxml.jackson.core:jackson-databind:2.7.2 -> 2.7.4
