### ISSUE TITLE
Whats the right version for everything : com.fasterxml.jackson related

### ISSUE THREAD

**Issue by vigneshsenapathy** [bitsofinfo/hazelcast-consul-discovery-spi#24]
Seems like the version for com.fasterxml.jackson is 2.7.4 and 2.72. Wanted to know whats the right version as i am kinda stuck on why things are not working for me. Is this for everything related to jackson or just to databind

**Comment by vigneshsenapathy** [comment]
I made all transient dependency to be 2.7.2 for jackson still i am getting the following error:
  	 line:	 {"level":"SEVERE","time":"Wed Sep 20 15:58:46 GMT 2017","source":"com.hazelcast.internal.cluster.impl.DiscoveryJoiner","logger_name":"com.hazelcast.internal.cluster.impl.DiscoveryJoiner","message":"[172.17.0.1]:5701 [hazelcast-consul-discovery-spi] [3.8.4] com.fasterxml.jackson.databind.type.ReferenceType.upgradeFrom(Lcom/fasterxml/jackson/databind/JavaType;Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/type/ReferenceType;","thrown":"	

below is my dependencies chain. I have made com.fasterxml.jackson.core:jackson-databind to be 2.7.2 and others to be 2.7.4 and that also didnt work
+--- com.hazelcast:hazelcast:3.7+ -> 3.7.8
+--- com.orbitz.consul:consul-client:0.13.12
|    +--- com.squareup.retrofit2:retrofit:2.1.0
|    |    \--- com.squareup.okhttp3:okhttp:3.3.0
|    |         \--- com.squareup.okio:okio:1.8.0
|    +--- com.squareup.retrofit2:converter-jackson:2.0.2
|    |    +--- com.squareup.retrofit2:retrofit:2.0.2 -> 2.1.0 (*)
|    |    \--- com.fasterxml.jackson.core:jackson-databind:2.7.2
|    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.7.0 -> 2.7.2
|    |         \--- com.fasterxml.jackson.core:jackson-core:2.7.2
|    +--- com.google.guava:guava:19.0
|    +--- com.google.code.findbugs:jsr305:1.3.9
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.7.4 -> 2.7.2
|    +--- com.fasterxml.jackson.core:jackson-core:2.7.4 -> 2.7.2
|    +--- com.fasterxml.jackson.core:jackson-databind:2.7.4 -> 2.7.2 (*)
|    +--- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.7.4 -> 2.7.2
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.7.2 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.7.2
|    |    \--- com.google.guava:guava:16.0 -> 19.0
|    +--- org.apache.commons:commons-lang3:3.4
|    \--- org.slf4j:slf4j-api:1.7.21
+--- commons-codec:commons-codec:1.8
+--- org.apache.cxf:cxf-rt-rs-client:3.0.3
|    +--- org.apache.cxf:cxf-rt-transports-http:3.0.3
|    |    \--- org.apache.cxf:cxf-core:3.0.3
|    |         +--- org.codehaus.woodstox:woodstox-core-asl:4.4.1
|    |         |    \--- org.codehaus.woodstox:stax2-api:3.1.4
|    |         \--- org.apache.ws.xmlschema:xmlschema-core:2.1.0
|    +--- org.apache.cxf:cxf-core:3.0.3 (*)
|    \--- org.apache.cxf:cxf-rt-frontend-jaxrs:3.0.3
|         +--- org.apache.cxf:cxf-core:3.0.3 (*)
|         +--- javax.ws.rs:javax.ws.rs-api:2.0.1
|         +--- javax.annotation:javax.annotation-api:1.2
|         \--- org.apache.cxf:cxf-rt-transports-http:3.0.3 (*)
+--- org.apache.cxf:cxf-rt-transports-http-hc:3.0.3
|    +--- org.apache.cxf:cxf-core:3.0.3 (*)
|    +--- org.apache.cxf:cxf-rt-transports-http:3.0.3 (*)
|    +--- org.slf4j:slf4j-api:1.7.7 -> 1.7.21
|    +--- org.apache.httpcomponents:httpcore-nio:4.3.3
|    |    \--- org.apache.httpcomponents:httpcore:4.3.3
|    \--- org.apache.httpcomponents:httpasyncclient:4.0.2
|         +--- org.apache.httpcomponents:httpcore:4.3.2 -> 4.3.3
|         +--- org.apache.httpcomponents:httpcore-nio:4.3.2 -> 4.3.3 (*)
|         \--- org.apache.httpcomponents:httpclient:4.3.5
|              +--- org.apache.httpcomponents:httpcore:4.3.2 -> 4.3.3
|              \--- commons-codec:commons-codec:1.6 -> 1.8
\--- junit:junit:4.12
     \--- org.hamcrest:hamcrest-core:1.3

**Comment by zambien** [comment]
Try this:

```
 wget --quiet http://central.maven.org/maven2/org/apache/cxf/cxf-rt-rs-client/3.0.3/cxf-rt-rs-client-3.0.3.jar
 wget --quiet http://central.maven.org/maven2/org/apache/cxf/cxf-rt-transports-http-hc/3.0.3/cxf-rt-transports-http-hc-3.0.3.jar
 wget --quiet http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.7.4/jackson-databind-2.7.4.jar
 wget --quiet http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.8.7/jackson-core-2.8.7.jar
 wget --quiet http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.7.4/jackson-annotations-2.7.4.jar
 wget --quiet http://central.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-guava/2.7.4/jackson-datatype-guava-2.7.4.jar
 wget --quiet http://central.maven.org/maven2/com/google/guava/guava/19.0/guava-19.0.jar
 wget --quiet http://central.maven.org/maven2/com/squareup/okhttp3/okhttp/3.2.0/okhttp-3.2.0.jar
 wget --quiet http://central.maven.org/maven2/com/squareup/retrofit2/converter-jackson/2.0.2/converter-jackson-2.0.2.jar
 wget --quiet http://central.maven.org/maven2/com/squareup/retrofit2/retrofit/2.1.0/retrofit-2.1.0.jar
 wget --quiet http://central.maven.org/maven2/com/orbitz/consul/consul-client/0.13.2/consul-client-0.13.2.jar
 wget --quiet http://central.maven.org/maven2/com/squareup/okio/okio/1.11.0/okio-1.11.0.jar
```

**Comment by vigneshsenapathy** [comment]
@zambien @bitsofinfo : if u have a working jar i can use let me know as i dont want to skip things from the project. Its easier to get a good working jar. Please let me know

**Comment by bitsofinfo** [comment]
@vigneshsenapathy the working jar is in maven central, nobody to my knowledge using this project is making special custom jar builds, but simply the existing facilities maven/gradle to exclude and resolve dependency conflicts like any other project.

**Comment by vigneshsenapathy** [comment]
@bitsofinfo : maven doesnt have a rc-7 which is what the code is it at correct?

**Comment by bitsofinfo** [comment]
Per the README you need to add bintray to your maven/gradle repos

https://bintray.com/bintray/jcenter?filterByPkgName=hazelcast-consul-discovery-spi
