### ISSUE TITLE
Hazelcast version

### ISSUE THREAD

**Issue by neterium-dev** [bitsofinfo/hazelcast-consul-discovery-spi#25]
Hi,

Is it possible to upgrade your hazelcast dependency to the latest stable version? (3.8+)

Thanks

**Comment by bitsofinfo** [comment]
The dependency is declared as `compile group: 'com.hazelcast', name: 'hazelcast', version:'3.7+'` so if you already have in a newer hazelcast in your own `build.gradle` that is referencing this library, that one should take precedence and be used instead.

**Comment by neterium-dev** [comment]
Yep sure, but for some reasons, Gradle keeps using 3.7.* as soon as I add this lib in the classpath:
org.bitsofinfo:hazelcast-consul-discovery-spi:1.0-RC7

I'm using vertx 3.5.0 which brings hazelcast 3.8.+, but it gets downgraded

 +--- io.vertx:vertx-hazelcast:3.5.0
|    |    +--- io.vertx:vertx-core:3.5.0 (*)
|    |    \--- com.hazelcast:hazelcast:3.8.2 -> 3.7.8


 +--- io.vertx:vertx-web-client:3.5.0 (*)
|    +--- org.bitsofinfo:hazelcast-consul-discovery-spi:1.0-RC7
|    |    +--- com.hazelcast:hazelcast:3.7+ -> 3.7.8

**Comment by bitsofinfo** [comment]
Just try excluding the transitive dependency this lib includes

**Comment by neterium-dev** [comment]
Thanks!
That's what I tries (hoping without mistakes), but had to eventually force the version:

compile group: 'com.hazelcast', name: 'hazelcast', version: '3.8.+'
compile ('org.bitsofinfo:hazelcast-consul-discovery-spi:1.0-RC7') {
    exclude group: 'com.hazelcast', module: 'hazelcast'
}

Note that the dependency issue comes from a transitive relationship:

bitsofinfo -> mysharedlib -> mymodule

in mysharedlib, when I inspect the deps, it's 3.8, but in mymodule it's 3.7 because of bitsinfo (as stated by Gradle)... Anyway, I suppose it's more a gradle issue than a problem in this library.
