### ISSUE TITLE
Replace deprecated 'script' w/ 'args'

### ISSUE THREAD

**Issue by bitsofinfo** [bitsofinfo/hazelcast-consul-discovery-spi#27]
Since consul 1.x - https://www.consul.io/api/agent/check.html#args

**Comment by Verdoso** [comment]
Hi there,
For what it's worth, I was able to get script checks to work with a consul 1.x simply by

1. Updating consul client version:
Build.gradle
compile group: 'com.orbitz.consul', name: 'consul-client', version:'0.17.1'
->
compile group: 'com.orbitz.consul', name: 'consul-client', version:'1.2.4'

2. Updating ScriptHealthCheckBuilder
ScriptHealthCheckBuilder.java
regCheck = Registration.RegCheck.script(healthCheckScript, healthCheckScriptIntervalSeconds);
->
regCheck = Registration.RegCheck.args(Arrays.asList(healthCheckScript.split(" ")), healthCheckScriptIntervalSeconds);

So it should be simple now that the client was updated. 
Cheers!

**Comment by bitsofinfo** [comment]
Great, can your please submit a pr?

**Comment by Verdoso** [comment]
Yeah, let me finish the [utility class that I've been creating to use it](https://github.com/Verdoso/GreenSummer/blob/master/summer-core/src/main/java/org/greeneyed/summer/config/HazelcastConsulSessionReplicationConfiguration.java) and see why some errors in the tests are failing, even before my modifications.
Cheers!

**Comment by Verdoso** [comment]
It seems problem was testing Script health check with nc and no nc installed. Running the tests now...

**Comment by Verdoso** [comment]
There you have it, PR #28
