### ISSUE TITLE
Add support for different kinds of checks in registrator

### ISSUE THREAD

**Issue by bitsofinfo** [bitsofinfo/hazelcast-consul-discovery-spi#3]
Should be able to do more than just "script", i.e. TCP/HTTP, which won't rely on something being available such as bash/curl etc. Add additional support for these checks in the `consul-registrator-config` JSON block such as:

```
"healthCheckType":"tcp",
"healthCheckTcp":"ip:port",
"healthCheckTcpIntervalSeconds":30
"healthCheckTcpTimeoutSeconds":30
```

```
"healthCheckType":"http",
"healthCheckHttp":"http://hostToCheck:port/whatever",
"healthCheckHttpIntervalSeconds":30
"healthCheckHttpTimeoutSeconds":30
```

https://www.consul.io/docs/agent/checks.html

https://github.com/hazelcast/hazelcast/issues/7381

**Comment by bmudda** [comment]
Currently there is no support for TCP health check on Orbitz client so we are only going to add http check until we implement the TCP health check on Orbitz client.

https://github.com/OrbitzWorldwide/consul-client/issues/103

**Comment by bmudda** [comment]
The HTTP health check currently only supports `http` and `interval` only. The `timeout` option is not yet supported.

``` java
public static RegCheck http(String http, long interval) {
        return ImmutableRegCheck
                .builder()
                .http(http)
                .interval(String.format("%ss", interval))
                .build();
}
```
