### ISSUE TITLE
instanceName must contain text

### ISSUE THREAD

**Issue by pchirumalla** [bitsofinfo/hazelcast-consul-discovery-spi#32]
Hello,

I have consul running on my localhost and below is how i have configured this plugin in my spring boot application.

@Bean
	public HazelcastInstance hazelcastInstance()  throws Exception{
		return Hazelcast.getOrCreateHazelcastInstance(buildHzConfig());
	}
	private Config buildHzConfig() throws Exception {

		Config config = new Config();

       // Use Consul for discovery instead of multicast with the help of this:
       // https://github.com/bitsofinfo/hazelcast-consul-discovery-spi

		config.setProperty("hazelcast.discovery.enabled", "true");
		config.setProperty("hazelcast.http.healthcheck.enabled", "true");

		config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
		String myIP = InetAddress.getLocalHost().getHostAddress();
		DiscoveryStrategyConfig discoveryStrategyConfig = new DiscoveryStrategyConfig(new ConsulDiscoveryStrategyFactory());
		discoveryStrategyConfig.addProperty(ConsulDiscoveryConfiguration.CONSUL_HOST.key(), myIP);
		discoveryStrategyConfig.addProperty(ConsulDiscoveryConfiguration.CONSUL_PORT.key(), "8500");
		discoveryStrategyConfig.addProperty(ConsulDiscoveryConfiguration.CONSUL_SERVICE_TAGS.key(), "");
		discoveryStrategyConfig.addProperty(ConsulDiscoveryConfiguration.CONSUL_SERVICE_NAME.key(), "hz-cluster");
		discoveryStrategyConfig.addProperty(ConsulDiscoveryConfiguration.CONSUL_HEALTHY_ONLY.key(), true);
		discoveryStrategyConfig.addProperty(ConsulDiscoveryConfiguration.CONSUL_DISCOVERY_DELAY_MS.key(), "3000");
		discoveryStrategyConfig.addProperty(ConsulDiscoveryConfiguration.CONSUL_REGISTRATOR.key(), LocalDiscoveryNodeRegistrator.class.getName());

		ObjectNode jsonRegistratorConfig = JsonNodeFactory.instance.objectNode();

		jsonRegistratorConfig.put("preferPublicAddress", false);
		jsonRegistratorConfig.put("healthCheckProvider", HttpHealthCheckBuilder.class.getName());
		jsonRegistratorConfig.put("healthCheckHttp", String.format("http://"+myIP+":%s%s", "8891", "/hazelcast/health"));
		jsonRegistratorConfig.put("healthCheckHttpIntervalSeconds", 3);

		discoveryStrategyConfig.addProperty(ConsulDiscoveryConfiguration.CONSUL_REGISTRATOR_CONFIG.key(), jsonRegistratorConfig.toString());

		config.getNetworkConfig().getJoin().getDiscoveryConfig().getDiscoveryStrategyConfigs().add(discoveryStrategyConfig);

		return config;
	}

When i start the application, below is the error i am getting. Can someone help with this. I am just wondering what this "instanceName must contain text" in the logs. I couldn't figure out anything by starting the application in debug mode (the frames doesn't link to the exact class)

ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource  [/com/api/SpringConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is java.lang.IllegalArgumentException: instanceName must contain text

Thanks

**Comment by bitsofinfo** [comment]
Please read the hazelcast docs etc, the issue is you are not setting a instance name for your hazelcast instance https://github.com/hazelcast/hazelcast/blob/86a759ac20eab87d7a249fa6c267a5f5ab4ad215/hazelcast/src/main/java/com/hazelcast/instance/impl/HazelcastInstanceFactory.java#L101
