### ISSUE TITLE
Is the project still being maintained?

### ISSUE THREAD

**Issue by lindahm** [bitsofinfo/hazelcast-consul-discovery-spi#38]
Hi
I was wondering if this project was still being maintained and if a non-RC version is planned for anytime in the future?
Just curious because seeing the last commit if from a year ago.

Would you advise to use it for production?

Thank you!

**Comment by bitsofinfo** [comment]
I have not used it in several years since I moved off of swarm and on to Kubernetes. We were using it in production as well as other user's of this project. There are no planned releases.

**Comment by lindahm** [comment]
Thanks for the fast response, appreciate it. Ok!
